Vani Jain
E19CSE019

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
# importing libraries for polynomial transform
from sklearn.preprocessing import PolynomialFeatures
# for creating pipeline
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline

In [2]:
from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

Mounted at /content/gdrive


In [3]:
data=pd.read_csv("/content/gdrive/MyDrive/csv_result-Behavior of the urban traffic.csv")

In [4]:
data.head()

id  Hour  ...  Intermittent_Semaphore  Slowness_in_traffic_percent
0   1  7:00  ...                     0.0                          4.1
1   2  7:30  ...                     0.0                          6.6
2   3  8:00  ...                     0.0                          8.7
3   4  8:30  ...                     0.0                          9.2
4   5  9:00  ...                     0.0                         11.1

[5 rows x 19 columns]

In [5]:
data=pd.get_dummies(data,columns=['Hour'],drop_first=True)
data.head()

id  Immobilized_bus  Broken_Truck  ...  Hour_8:30  Hour_9:00  Hour_9:30
0   1              0.0           0.0  ...          0          0          0
1   2              0.0           0.0  ...          0          0          0
2   3              0.0           0.0  ...          0          0          0
3   4              0.0           0.0  ...          1          0          0
4   5              0.0           0.0  ...          0          1          0

[5 rows x 44 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 44 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     135 non-null    int64  
 1   Immobilized_bus                        135 non-null    float64
 2   Broken_Truck                           135 non-null    float64
 3   Vehicle_excess                         135 non-null    float64
 4   Accident_victim                        135 non-null    float64
 5   Running_over                           135 non-null    float64
 6   Fire_vehicles                          135 non-null    float64
 7   Occurrence_involving_freight           135 non-null    float64
 8   Incident_involving_dangerous_freight   135 non-null    float64
 9   Lack_of_electricity                    135 non-null    float64
 10  Fire                                   135 non-null    float64
 11  Point_

In [7]:
X=data.drop(['Slowness_in_traffic_percent','id'],axis=1).values
y=data['Slowness_in_traffic_percent'].values

In [8]:
X_shape=X.shape
X_type  = type(X)
y_shape = y.shape
y_type  = type(y)
print(f'X: Type-{X_type}, Shape-{X_shape}')
print(f'y: Type-{y_type}, Shape-{y_shape}')

X: Type-<class 'numpy.ndarray'>, Shape-(135, 42)
y: Type-<class 'numpy.ndarray'>, Shape-(135,)


In [9]:
# Split the dataset into training and testing here
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [10]:
X_train_shape = X_train.shape
y_train_shape = y_train.shape
X_test_shape  = X_test.shape
y_test_shape  = y_test.shape

print(f"X_train: {X_train_shape} , y_train: {y_train_shape}")
print(f"X_test: {X_test_shape} , y_test: {y_test_shape}")

X_train: (108, 42) , y_train: (108,)
X_test: (27, 42) , y_test: (27,)


Linear Regression

In [11]:
model = LinearRegression(fit_intercept=True)

In [12]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
y_pred = model.predict(X_test)

In [14]:
mse = np.mean( (y - model.predict(X))**2 )
print("MSE:",mse)

MSE: 5.091807078854171


In [15]:
from sklearn.metrics import mean_absolute_error
print("Mean absolute error: ")
mean_absolute_error(y_test, y_pred)

Mean absolute error: 


2.809458545067806

In [16]:
from sklearn.metrics import median_absolute_error
print("Median absolute error: ")
median_absolute_error(y_test, y_pred)

Median absolute error: 


2.166830171051224

In [17]:
from sklearn.metrics import mean_squared_log_error
print("Mean squared logarithmic error: ")
mean_squared_log_error(y_test, y_pred)

Mean squared logarithmic error: 


0.10101311810989103

In [18]:
from sklearn.metrics import max_error
print("Max error: ")
max_error(y_test, y_pred)

Max error: 


7.963189885259467

In [19]:
from sklearn.metrics import explained_variance_score
print("Explained variance score: ")
explained_variance_score(y_test, y_pred)

Explained variance score: 


0.24871772877689335

In [20]:
from sklearn.metrics import r2_score
print("r2 score: ")
r2_score(y_test, y_pred)

r2 score: 


0.23530838731669124

Degree 2 - Polynomial Regression

In [22]:
degree=2
polyreg=make_pipeline(PolynomialFeatures(degree),LinearRegression())
polyreg.fit(X,y)
y_pred=polyreg.predict(X_test)
print("MSE:")
mean_squared_error(y_test,y_pred)

MSE:


0.5616738429334432

In [23]:
print("Median absolute error: ")
median_absolute_error(y_test, y_pred)

Median absolute error: 


0.0034301757812498224

In [24]:
print("Mean absolute error: ")
mean_absolute_error(y_test, y_pred)

Mean absolute error: 


0.19515064380787053

In [25]:
print("Mean squared logarithmic error: ")
mean_squared_log_error(y_test, y_pred)

Mean squared logarithmic error: 


0.002982273165778329

In [26]:
print("Max error: ")
max_error(y_test, y_pred)

Max error: 


3.5511596679687507

In [27]:
print("Explained variance score: ")
explained_variance_score(y_test, y_pred)

Explained variance score: 


0.967144236753845

In [28]:
print("r2 score:")
r2_score(y_test,y_pred)

r2 score:


0.9648275971266226

Playing With Model

In [29]:
X=data.drop(['Slowness_in_traffic_percent','id','Lack_of_electricity','Fire','Semaphore_off'],axis=1).values
Y=data['Slowness_in_traffic_percent'].values

In [30]:
X_shape = X.shape
X_type  = type(X)
y_shape = y.shape
y_type  = type(y)
print(f'X: Type-{X_type}, Shape-{X_shape}')
print(f'y: Type-{y_type}, Shape-{y_shape}')

X: Type-<class 'numpy.ndarray'>, Shape-(135, 39)
y: Type-<class 'numpy.ndarray'>, Shape-(135,)


In [31]:
# Split the dataset into training and testing here
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)
X_train_shape = X_train.shape
y_train_shape = y_train.shape
X_test_shape  = X_test.shape
y_test_shape  = y_test.shape

print(f"X_train: {X_train_shape} , y_train: {y_train_shape}")
print(f"X_test: {X_test_shape} , y_test: {y_test_shape}")

X_train: (108, 39) , y_train: (108,)
X_test: (27, 39) , y_test: (27,)


In [32]:
model = LinearRegression(fit_intercept=True)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = np.mean( (y - model.predict(X))**2 )
print("MSE:",mse)

MSE: 5.525011807471965


In [33]:
from sklearn.metrics import mean_absolute_error
print("Mean absolute error: ")
mean_absolute_error(y_test, y_pred)

Mean absolute error: 


2.886998719474469

In [34]:
from sklearn.metrics import median_absolute_error
print("Median absolute error: ")
median_absolute_error(y_test, y_pred)

Median absolute error: 


3.0414094805100973

In [35]:
from sklearn.metrics import mean_squared_log_error
print("Mean squared logarithmic error: ")
mean_squared_log_error(y_test, y_pred)

Mean squared logarithmic error: 


0.10358065508478008

In [36]:
from sklearn.metrics import max_error
print("Max error: ")
max_error(y_test, y_pred)

Max error: 


7.913861259607538

In [37]:
from sklearn.metrics import explained_variance_score
print("Explained variance score: ")
explained_variance_score(y_test, y_pred)

Explained variance score: 


0.22090715691163987

In [38]:
from sklearn.metrics import r2_score
print("r2 score: ")
r2_score(y_test, y_pred)

r2 score: 


0.19895007370330564

After removing the following three features: lack of electricity, fire, semaphore the errorof the model has increased

Normalization

In [39]:
from sklearn import preprocessing
d = preprocessing.normalize(data, axis=1)
names = data.columns
scaled_df = pd.DataFrame(d, columns=names)
scaled_df.head()

id  Immobilized_bus  Broken_Truck  ...  Hour_8:30  Hour_9:00  Hour_9:30
0  0.230571              0.0           0.0  ...    0.00000   0.000000        0.0
1  0.287006              0.0           0.0  ...    0.00000   0.000000        0.0
2  0.324083              0.0           0.0  ...    0.00000   0.000000        0.0
3  0.396760              0.0           0.0  ...    0.09919   0.000000        0.0
4  0.409328              0.0           0.0  ...    0.00000   0.081866        0.0

[5 rows x 44 columns]

In [40]:
X=data.drop(['Slowness_in_traffic_percent','id'],axis=1).values
y=data['Slowness_in_traffic_percent'].values

In [41]:
X_shape = X.shape
X_type  = type(X)
y_shape = y.shape
y_type  = type(y)
print(f'X: Type-{X_type}, Shape-{X_shape}')
print(f'y: Type-{y_type}, Shape-{y_shape}')

X: Type-<class 'numpy.ndarray'>, Shape-(135, 42)
y: Type-<class 'numpy.ndarray'>, Shape-(135,)


In [42]:
# Split the dataset into training and testing here
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)
X_train_shape = X_train.shape
y_train_shape = y_train.shape
X_test_shape  = X_test.shape
y_test_shape  = y_test.shape

print(f"X_train: {X_train_shape} , y_train: {y_train_shape}")
print(f"X_test: {X_test_shape} , y_test: {y_test_shape}")

X_train: (108, 42) , y_train: (108,)
X_test: (27, 42) , y_test: (27,)


In [43]:
model = LinearRegression(fit_intercept=True)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = np.mean( (y - model.predict(X))**2 )
print("MSE:",mse)

MSE: 5.091807078854171


In [44]:
from sklearn.metrics import mean_absolute_error
print("Mean absolute error: ")
mean_absolute_error(y_test, y_pred)

Mean absolute error: 


2.809458545067806

In [45]:
from sklearn.metrics import median_absolute_error
print("Median absolute error: ")
median_absolute_error(y_test, y_pred)

Median absolute error: 


2.166830171051224

In [46]:
from sklearn.metrics import mean_squared_log_error
print("Mean squared logarithmic error: ")
mean_squared_log_error(y_test, y_pred)

Mean squared logarithmic error: 


0.10101311810989103

In [47]:
from sklearn.metrics import max_error
print("Max error: ")
max_error(y_test, y_pred)

Max error: 


7.963189885259467

In [48]:
from sklearn.metrics import explained_variance_score
print("Explained variance score: ")
explained_variance_score(y_test, y_pred)

Explained variance score: 


0.24871772877689335

In [49]:
from sklearn.metrics import r2_score
print("r2 score: ")
r2_score(y_test, y_pred)

r2 score: 


0.23530838731669124

Shuffling traing samples

In [50]:
# Split the dataset into training and testing here
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=123)
X_train_shape = X_train.shape
y_train_shape = y_train.shape
X_test_shape  = X_test.shape
y_test_shape  = y_test.shape

print(f"X_train: {X_train_shape} , y_train: {y_train_shape}")
print(f"X_test: {X_test_shape} , y_test: {y_test_shape}")

X_train: (108, 42) , y_train: (108,)
X_test: (27, 42) , y_test: (27,)


In [51]:
model = LinearRegression(fit_intercept=True)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
mse = np.mean( (y - model.predict(X))**2 )
print("MSE:",mse)

MSE: 4.924662583437977


In [52]:
from sklearn.metrics import mean_absolute_error
print("Mean absolute error: ")
mean_absolute_error(y_test, y_pred)

Mean absolute error: 


2.3079184700780275

In [53]:
from sklearn.metrics import median_absolute_error
print("Median absolute error: ")
median_absolute_error(y_test, y_pred)

Median absolute error: 


1.573451382673575

In [54]:
from sklearn.metrics import mean_squared_log_error
print("Mean squared logarithmic error: ")
mean_squared_log_error(y_test, y_pred)

Mean squared logarithmic error: 


0.06805281413255128

In [55]:
from sklearn.metrics import max_error
print("Max error: ")
max_error(y_test, y_pred)

Max error: 


9.5356867724017

In [56]:
from sklearn.metrics import explained_variance_score
print("Explained variance score: ")
explained_variance_score(y_test, y_pred)

Explained variance score: 


0.5030858894489112

In [57]:
from sklearn.metrics import r2_score
print("r2 score: ")
r2_score(y_test, y_pred)

r2 score: 


0.4831851264723166

After shuffling training samples, both Mean Absolute error and Median Absolute error have reduced

Degree 3

In [58]:
degree=3
polyreg=make_pipeline(PolynomialFeatures(degree),LinearRegression())
polyreg.fit(X,y)
y_pred=polyreg.predict(X_test)
print("MSE:")
mean_squared_error(y_test,y_pred)

MSE:


0.16940711687215504

In [59]:
print("Median absolute error: ")
median_absolute_error(y_test, y_pred)

Median absolute error: 


0.0030609130859371447

In [60]:
print("Mean absolute error: ")
mean_absolute_error(y_test, y_pred)

Mean absolute error: 


0.1357051142939813

In [61]:
print("Mean squared logarithmic error: ")
mean_squared_log_error(y_test, y_pred)

Mean squared logarithmic error: 


0.0013801124979989528

In [62]:
print("Max error: ")
max_error(y_test, y_pred)

Max error: 


1.6479553222656254

In [63]:
print("Explained variance score: ")
explained_variance_score(y_test, y_pred)

Explained variance score: 


0.991081597852299

In [64]:
print("r2 score:")
r2_score(y_test,y_pred)

r2 score:


0.9906791167569236

After increasing the value of polynomial most values of the metrics have become better

Classification Metrics

In [65]:
from sklearn.linear_model import LogisticRegression
data = pd.read_csv("/content/gdrive/MyDrive/diabetes_data.csv")
data.head()

Age Gender Polyuria Polydipsia  ... muscle stiffness Alopecia Obesity     class
0   40   Male       No        Yes  ...              Yes      Yes     Yes  Positive
1   58   Male       No         No  ...               No      Yes      No  Positive
2   41   Male      Yes         No  ...              Yes      Yes      No  Positive
3   45   Male       No         No  ...               No       No      No  Positive
4   60   Male      Yes        Yes  ...              Yes      Yes     Yes  Positive

[5 rows x 17 columns]

In [66]:
from sklearn import preprocessing   #.apply() for single line
label_encoder = preprocessing.LabelEncoder()

data['Gender']= label_encoder.fit_transform(data['Gender'])
data['Polyuria']= label_encoder.fit_transform(data['Polyuria'])
data['Polydipsia']= label_encoder.fit_transform(data['Polydipsia'])
data['sudden weight loss']= label_encoder.fit_transform(data['sudden weight loss'])
data['weakness']= label_encoder.fit_transform(data['weakness'])
data['Polyphagia']= label_encoder.fit_transform(data['Polyphagia'])
data['Genital thrush']= label_encoder.fit_transform(data['Genital thrush'])
data['visual blurring']= label_encoder.fit_transform(data['visual blurring'])
data['Itching']= label_encoder.fit_transform(data['Itching'])
data['Irritability']= label_encoder.fit_transform(data['Irritability'])
data['delayed healing']= label_encoder.fit_transform(data['delayed healing'])
data['partial paresis']= label_encoder.fit_transform(data['partial paresis'])
data['muscle stiffness']= label_encoder.fit_transform(data['muscle stiffness'])
data['Alopecia']= label_encoder.fit_transform(data['Alopecia'])
data['Obesity']= label_encoder.fit_transform(data['Obesity'])
data['class']= label_encoder.fit_transform(data['class'])
data.head()

Age  Gender  Polyuria  ...  Alopecia  Obesity  class
0   40       1         0  ...         1        1      1
1   58       1         0  ...         1        0      1
2   41       1         1  ...         1        0      1
3   45       1         0  ...         0        0      1
4   60       1         1  ...         1        1      1

[5 rows x 17 columns]

In [67]:
normalize=(data.iloc[:,1]-data.iloc[:,1].mean())/data.iloc[:,1].std()
#normalized_df=(df-df.mean())/df.std()
data.insert(1, 'age normalize', normalize)
data.head()

Age  age normalize  Gender  ...  Alopecia  Obesity  class
0   40       0.764356       1  ...         1        1      1
1   58       0.764356       1  ...         1        0      1
2   41       0.764356       1  ...         1        0      1
3   45       0.764356       1  ...         0        0      1
4   60       0.764356       1  ...         1        1      1

[5 rows x 18 columns]

In [68]:
# Define your X and y
X = data.drop(["class","Age"], axis = 1).values
y = data['class'].values

In [69]:
# Split the dataset into training and testing here
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=123)

In [70]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [71]:
# Fit the model
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [72]:
# Predict on testing set X_test
y_pred = model.predict(X_test)

In [73]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 76,   9],
       [  9, 114]])

In [74]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred, average=None)

array([0.89411765, 0.92682927])

In [75]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred, average=None)

array([0.89411765, 0.92682927])

In [76]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average=None)

array([0.89411765, 0.92682927])